CREATE PROC sp_Admin_LayThongKe

AS
BEGIN
    SET NOCOUNT ON;
    SELECT
    (SELECT COUNT(IDBanSao) FROM BAN_SAO_SAN_PHAM SP) AS TongSP,
    (SELECT COUNT(IDTaiKhoan)FROM TAI_KHOAN  )AS TongTK ,
    (SELECT COUNT(IDDonHang)FROM DON_HANG)  AS TongDH ,
    (SELECT COUNT(IDShop) FROM SHOP) AS TongShop;
END 