USE ShopeeVipDB
GO
-- 1. Bảng Tài khoản
CREATE TABLE TAI_KHOAN (
    IDTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap VARCHAR(30) UNIQUE,
    Ten NVARCHAR(50),
    SDT VARCHAR(10),
    Email VARCHAR(255),
    GioiTinh INT,
    MatKhau VARCHAR(100)
);

-- 2. Bảng Người Mua
CREATE TABLE NGUOI_MUA (
    IDNguoiMua INT IDENTITY(1,1) PRIMARY KEY ,
    IDTaiKhoan INT FOREIGN KEY REFERENCES TAI_KHOAN(IDTaiKhoan) UNIQUE,
    TrangThai INT
);

-- 3. Bảng Shop
CREATE TABLE SHOP (
    IDShop INT IDENTITY(1,1) PRIMARY KEY,
    IDTaiKhoan INT FOREIGN KEY REFERENCES TAI_KHOAN(IDTaiKhoan) UNIQUE,
    TrangThai INT
);

CREATE TABLE TK_NGAN_HANG
(
    IDNganHang INT IDENTITY(1,1) PRIMARY KEY,
    STK VARCHAR(20),
    TenNganHang NVARCHAR(50),
    SoDu DECIMAL(18,2),
    IDShop INT FOREIGN KEY REFERENCES SHOP(IDShop) 
)

CREATE TABLE GIAO_DICH
(
    IDGiaoDich INT IDENTITY(1,1) PRIMARY KEY,
    ThoiGianGD DATE,
    MaGD VARCHAR(20),
    NoiDung NVARCHAR(MAX),
    SoTien DECIMAL(18,2),
    LoaiGD BIT,
    
    IDShop INT FOREIGN KEY REFERENCES SHOP(IDShop) UNIQUE
)

-- 4. Bảng Danh Mục
CREATE TABLE DANH_MUC (
    IDDanhMuc INT IDENTITY(1,1) PRIMARY KEY,
    TenLoai NVARCHAR(50)
);

-- 5. Bảng Sản Phẩm
CREATE TABLE SAN_PHAM (
    IDSanPham INT IDENTITY(1,1) PRIMARY KEY,
    IDShop INT FOREIGN KEY REFERENCES SHOP(IDShop),
    IDDanhMuc INT FOREIGN KEY REFERENCES DANH_MUC(IDDanhMuc),
    TenSanPham NVARCHAR(50),
    MoTa NVARCHAR(MAX),
    HinhAnh VARCHAR(255)
);

-- 6. Bảng Bản Sao Sản Phẩm (Biến thể)
CREATE TABLE BAN_SAO_SAN_PHAM (
    IDBanSao INT IDENTITY(1,1) PRIMARY KEY,
    IDSanPham INT FOREIGN KEY REFERENCES SAN_PHAM(IDSanPham),
    SoLuongTonKho INT,
    GiaBan DECIMAL(18,2),
    BienThe NVARCHAR(50), -- Ví dụ: Màu Đỏ, Size L
    HinhAnh VARCHAR(MAX),
    TrangThai INT
);

-- 7. Bảng Đơn Hàng
CREATE TABLE DON_HANG (
    IDDonHang INT IDENTITY(1,1) PRIMARY KEY,
    IDNguoiMua INT FOREIGN KEY REFERENCES NGUOI_MUA(IDNguoiMua)
);

-- 8. Bảng Chi Tiết Đơn Hàng
CREATE TABLE CHI_TIET_DON_HANG (
    IDChiTiet INT IDENTITY(1,1) PRIMARY KEY,
    IDDonHang INT FOREIGN KEY REFERENCES DON_HANG(IDDonHang),
    IDBanSao INT FOREIGN KEY REFERENCES BAN_SAO_SAN_PHAM(IDBanSao),
    TongTien DECIMAL(18,2), -- Nên hiểu là Giá tại thời điểm mua
    GhiChu NVARCHAR(200),
    SoLuong INT,
    TrangThai INT,
    GiaTien DECIMAL(18,2)
);

-- 9. Bảng Giỏ Hàng (PK phức hợp theo ảnh của bạn)
CREATE TABLE GIO_HANG (
    IDTaiKhoan INT,
    IDBanSao INT,
    SoLuongMua INT,
    NgayThem DATETIME DEFAULT GETDATE(),
    PRIMARY KEY (IDTaiKhoan, IDBanSao),
    FOREIGN KEY (IDTaiKhoan) REFERENCES TAI_KHOAN(IDTaiKhoan),
    FOREIGN KEY (IDBanSao) REFERENCES BAN_SAO_SAN_PHAM(IDBanSao)
);
GO

-- DELETE FOR TEST ---
DROP TABLE GIO_HANG;
DROP TABLE CHI_TIET_DON_HANG;
DROP TABLE DON_HANG;
DROP TABLE BAN_SAO_SAN_PHAM;
DROP TABLE SAN_PHAM;
DROP TABLE DANH_MUC;
DROP TABLE  GIAO_DICH;
DROP TABLE TK_NGAN_HANG;
DROP TABLE SHOP;
DROP TABLE NGUOI_MUA;
DROP TABLE TAI_KHOAN;