### POST Đăng kí
POST http://localhost:3000/dangKi
content-type: application/json

{
    "name": "Đỗ Toàn",
    "username": "toan123",
    "password": "01234",
    "phone": "0000",
    "email": "toan@gmail.com",
    "gender": "1",
    "role": "2"
}

### POST Đăng nhập

POST http://localhost:3000/
Content-Type: application/json

{
    "username": "tien1234",
    "password": "123456"
}

### GET Danh sách sản phẩm
GET http://localhost:3000/sanpham
Content-Type: application/json

{}

### [GET] Lấy chi tiết sản phẩm 
GET  http://localhost:3000/sanpham/3
Content-Type: application/json

{}