### POST Đăng kí
POST http://localhost:3000/dangKi
content-type: application/json

{
    "name": "Đỗ Toàn",
    "username": "toan123",
    "password": "01234",
    "phone": "0000",
    "email": "toan@gmail.com",
    "gender": "1",
    "role": "2"
}

### POST Đăng nhập

POST http://localhost:3000/
Content-Type: application/json

{
    "username": "tien1234",
    "password": "123456"
}

### GET Danh sách sản phẩm
GET http://localhost:3000/sanpham
Content-Type: application/json

{}

### [GET] Lấy chi tiết sản phẩm 
GET  http://localhost:3000/sanpham/3
Content-Type: application/json

{}


### [GET] Lấy giỏ hàng
GET http://localhost:3000/giohang/1
Content-Type: application/json

{}

### [POST] Thêm vào giỏ hàng
POST http://localhost:3000/giohang/themsanpham
Content-Type: application/json

{
    "userID": "1",
    "copyID": "2",
    "quantity": "1"
}

### [POST] Cập nhật giỏ hàng
POST http://localhost:3000/giohang/capnhatgiohang
Content-Type: application/json

{
    "userID": "1",
    "copyID": "1",
    "newQuantity": "2"
}